

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	int32_t capacity;
	int32_t len;
	uint8_t *data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

// Task defined in Rust that Go executes
typedef void (*RustTaskCallback)(const void *, int8_t);

// Callback to execute Rust tasks using a Go routine
//
// Args:
//   executor: ForeignExecutor lowered into a uint64_t value
//   delay: Delay in MS
//   task: RustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*ForeignExecutorCallback)(uint64_t, uint32_t, RustTaskCallback, void *);

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

// Continuation callback for UniFFI Futures
typedef void (*RustFutureContinuation)(void * , int8_t);

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Needed because we can't execute the callback directly from go.
void cgo_rust_task_callback_bridge_rustpushgo(RustTaskCallback, const void *, int8_t);

int8_t uniffiForeignExecutorCallbackrustpushgo(uint64_t, uint32_t, RustTaskCallback, void*);

void uniffiFutureContinuationCallbackrustpushgo(void*, int8_t);

void uniffi_rustpushgo_fn_free_client(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_diag_full_count(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_download_attachment(
	void* ptr,
	RustBuffer record_name,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_dump_chats_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_fetch_recent_messages(
	void* ptr,
	uint64_t since_timestamp_ms,
	RustBuffer chat_id,
	uint32_t max_pages,
	uint32_t max_results,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_sync_attachments(
	void* ptr,
	RustBuffer continuation_token,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_sync_chats(
	void* ptr,
	RustBuffer continuation_token,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_cloud_sync_messages(
	void* ptr,
	RustBuffer continuation_token,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_contacts_url(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_dsid(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_handles(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_get_icloud_auth_headers(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_attachment(
	void* ptr,
	RustBuffer conversation,
	RustBuffer data,
	RustBuffer mime,
	RustBuffer uti_type,
	RustBuffer filename,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_delivery_receipt(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_edit(
	void* ptr,
	RustBuffer conversation,
	RustBuffer target_uuid,
	uint64_t edit_part,
	RustBuffer new_text,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_message(
	void* ptr,
	RustBuffer conversation,
	RustBuffer text,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_read_receipt(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustBuffer for_uuid,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_tapback(
	void* ptr,
	RustBuffer conversation,
	RustBuffer target_uuid,
	uint64_t target_part,
	uint32_t reaction,
	RustBuffer emoji,
	int8_t remove,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_typing(
	void* ptr,
	RustBuffer conversation,
	int8_t typing,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_unsend(
	void* ptr,
	RustBuffer conversation,
	RustBuffer target_uuid,
	uint64_t edit_part,
	RustBuffer handle,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_send_move_to_recycle_bin(
	void* ptr,
	RustBuffer conversation,
	RustBuffer handle,
	RustBuffer chat_guid,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_delete_cloud_chats(
	void* ptr,
	RustBuffer chat_ids,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_stop(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_test_cloud_messages(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_client_validate_targets(
	void* ptr,
	RustBuffer targets,
	RustBuffer handle,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_loginsession(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_loginsession_finish(
	void* ptr,
	void* config,
	void* connection,
	RustBuffer existing_identity,
	RustBuffer existing_users,
	RustCallStatus* out_status
);

int8_t uniffi_rustpushgo_fn_method_loginsession_needs_2fa(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_loginsession_submit_2fa(
	void* ptr,
	RustBuffer code,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedapsconnection(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedapsconnection_state(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedapsstate(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_constructor_wrappedapsstate_new(
	RustBuffer string,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedapsstate_to_string(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedidsngmidentity(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_constructor_wrappedidsngmidentity_new(
	RustBuffer string,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsngmidentity_to_string(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedidsusers(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_constructor_wrappedidsusers_new(
	RustBuffer string,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsusers_get_handles(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsusers_login_id(
	void* ptr,
	uint64_t i,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedidsusers_to_string(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_rustpushgo_fn_method_wrappedidsusers_validate_keystore(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedosconfig(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_rustpushgo_fn_method_wrappedosconfig_get_device_id(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_free_wrappedtokenprovider(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_contacts_url(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_dsid(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_escrow_devices(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_icloud_auth_headers(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_get_mme_delegate_json(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_join_keychain_clique(
	void* ptr,
	RustBuffer passcode,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_join_keychain_clique_for_device(
	void* ptr,
	RustBuffer passcode,
	uint32_t device_index,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_method_wrappedtokenprovider_seed_mme_delegate_json(
	void* ptr,
	RustBuffer json,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_init_callback_messagecallback(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_init_callback_updateuserscallback(
	ForeignCallback callback_stub,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_connect(
	void* config,
	void* state,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_config_from_hardware_key(
	RustBuffer base64_key,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_config_from_hardware_key_with_device_id(
	RustBuffer base64_key,
	RustBuffer device_id,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_local_macos_config(
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_create_local_macos_config_with_device_id(
	RustBuffer device_id,
	RustCallStatus* out_status
);

void uniffi_rustpushgo_fn_func_init_logger(
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_login_start(
	RustBuffer apple_id,
	RustBuffer password,
	void* config,
	void* connection,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_new_client(
	void* connection,
	void* users,
	void* identity,
	void* config,
	RustBuffer token_provider,
	uint64_t message_callback,
	uint64_t update_users_callback,
	RustCallStatus* out_status
);

void* uniffi_rustpushgo_fn_func_restore_token_provider(
	void* config,
	void* connection,
	RustBuffer username,
	RustBuffer hashed_password_hex,
	RustBuffer pet,
	RustBuffer spd_base64,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rustbuffer_alloc(
	int32_t size,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rustbuffer_from_bytes(
	ForeignBytes bytes,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rustbuffer_free(
	RustBuffer buf,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rustbuffer_reserve(
	RustBuffer buf,
	int32_t additional,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_continuation_callback_set(
	RustFutureContinuation callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u8(
	void* handle,
	RustCallStatus* out_status
);

uint8_t ffi_rustpushgo_rust_future_complete_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i8(
	void* handle,
	RustCallStatus* out_status
);

int8_t ffi_rustpushgo_rust_future_complete_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u16(
	void* handle,
	RustCallStatus* out_status
);

uint16_t ffi_rustpushgo_rust_future_complete_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i16(
	void* handle,
	RustCallStatus* out_status
);

int16_t ffi_rustpushgo_rust_future_complete_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u32(
	void* handle,
	RustCallStatus* out_status
);

uint32_t ffi_rustpushgo_rust_future_complete_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i32(
	void* handle,
	RustCallStatus* out_status
);

int32_t ffi_rustpushgo_rust_future_complete_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_u64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_u64(
	void* handle,
	RustCallStatus* out_status
);

uint64_t ffi_rustpushgo_rust_future_complete_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_i64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_i64(
	void* handle,
	RustCallStatus* out_status
);

int64_t ffi_rustpushgo_rust_future_complete_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_f32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_f32(
	void* handle,
	RustCallStatus* out_status
);

float ffi_rustpushgo_rust_future_complete_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_f64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_f64(
	void* handle,
	RustCallStatus* out_status
);

double ffi_rustpushgo_rust_future_complete_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_pointer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_pointer(
	void* handle,
	RustCallStatus* out_status
);

void* ffi_rustpushgo_rust_future_complete_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_rust_buffer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

RustBuffer ffi_rustpushgo_rust_future_complete_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_poll_void(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_cancel_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_free_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_rustpushgo_rust_future_complete_void(
	void* handle,
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_connect(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_config_from_hardware_key(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_config_from_hardware_key_with_device_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_local_macos_config(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_create_local_macos_config_with_device_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_init_logger(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_login_start(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_new_client(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_func_restore_token_provider(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_diag_full_count(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_download_attachment(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_dump_chats_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_fetch_recent_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_sync_attachments(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_sync_chats(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_cloud_sync_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_contacts_url(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_dsid(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_handles(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_get_icloud_auth_headers(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_attachment(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_delivery_receipt(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_edit(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_message(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_read_receipt(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_tapback(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_typing(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_unsend(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_send_move_to_recycle_bin(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_delete_cloud_chats(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_stop(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_test_cloud_messages(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_client_validate_targets(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_loginsession_finish(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_loginsession_needs_2fa(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_loginsession_submit_2fa(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedapsconnection_state(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedapsstate_to_string(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsngmidentity_to_string(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_get_handles(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_login_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_to_string(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedidsusers_validate_keystore(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedosconfig_get_device_id(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_contacts_url(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_dsid(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_escrow_devices(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_icloud_auth_headers(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_get_mme_delegate_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_join_keychain_clique(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_join_keychain_clique_for_device(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_wrappedtokenprovider_seed_mme_delegate_json(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_constructor_wrappedapsstate_new(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_constructor_wrappedidsngmidentity_new(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_constructor_wrappedidsusers_new(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_messagecallback_on_message(
	RustCallStatus* out_status
);

uint16_t uniffi_rustpushgo_checksum_method_updateuserscallback_update_users(
	RustCallStatus* out_status
);

uint32_t ffi_rustpushgo_uniffi_contract_version(
	RustCallStatus* out_status
);


int32_t rustpushgo_cgo_MessageCallback(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);
int32_t rustpushgo_cgo_UpdateUsersCallback(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

